route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: 'email'
    email_configs:
    - to: 'tomer-example@company.com'
      from: 'tomer-example@company.info'
      smarthost: '<SMTP-SERVER:PORT>'
      auth_username: '<AUTH_USER>'
      auth_password: '<AUTH_PASSWORD>'
      send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
